name: Build Ryanair interconnected flight task

on:
  push:
    branches:
        - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '22'
          cache: 'maven'
      - name: Build with Maven
        run: mvn clean package -B

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: built-jar
          path: target/*.jar
          retention-days: 7